controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_secure:
    resource: ../src/Controller/Secure
    prefix: /secure
    type: attribute

app_admin:
    resource: ../src/Controller/Admin
    prefix: /admin
    type: attribute

app_public:
    resource: ../src/Controller/Public
    prefix: /public
    type: attribute
